package telas;

import javax.swing.JOptionPane;


public class Senador extends javax.swing.JFrame {
  
    private  final String[] senador= {"Alex","Luiz","Rita","Sandra","Katia"} ;
    private  final String [] nomepartido = {"Verde","Azul","Amarelo","Preto","Rosa"}; 
    private  final int[] numpartido ={11,12,13,14,15};
    private  final int[] num={110,120,130,140,150};
    private  int[] qVotos=new int[5];
    
  
    
   
    //variável auxiliar para verificar o número do partido
    private boolean partido=false;
    
    //usar para conferir se o eleitor votou nulo ou branco
    private boolean numBranco;
    private boolean auxBranco;
    private boolean numNulo;
    
    
    //contabilizar a quantidade do votos nulos e brancos 
    private int branco;
    private int nulo;
    
   
    
    
   
    private int concluir=0;
    int aux=0;
   
    /*-------------------------------------------------------------------------*/
    
    public String[] getsenador(){
        return senador;
    }
    
    public int[] getqVotos(){
        return qVotos;
    }
    
    public int getqNulo(){
        return nulo;
    }
    public int getBranco(){
        return branco;
    }
    
    
    /*inicializar a tela*/
    
    public void inicializar(){
        
        nulo=0;
        branco=0;
        auxBranco=false;
        numNulo=false;
        numBranco=false;
        
        for(int i=0;i<qVotos.length;i++){
            qVotos[i]=0;
        }
      
        
        Partido.setText("");
        nomePartido.setText("");
        Nome.setText("");
        nomeCand.setText("");
        AUX.setText("");
    }
    
   
    
    //valida o voto
    public void validacao(int voto) {
        
        numNulo=true;
            

        //confirma voto e atualiza a quantidade de voto do candidato em questão!
        for(int i=0;i<5;i++) {
                if(voto==num[i]) {
                qVotos[i]++;

                numNulo=false;
                

                }
        }  

        //voto será anulado e atualiza o numéro de votos anulados!
        if(numNulo==true) {
                
                nulo++;     
                numNulo=false;
               

        }
   

    }
    
    public void validaBranco(boolean aux){
        
        if(aux=true){
            numBranco=true;
        }
        
        if(numBranco==true) {
            branco++;
            
            numBranco=false;
            
        }
      
    }
    
    public int getconcluir(){
        return concluir;
    }
    
     public Senador() {
        initComponents();
        inicializar();
        concluir=0;
        
        
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        num1 = new javax.swing.JTextField();
        num3 = new javax.swing.JTextField();
        num2 = new javax.swing.JTextField();
        lblvotop = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Partido = new javax.swing.JLabel();
        nomePartido = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Nome = new javax.swing.JLabel();
        nomeCand = new javax.swing.JLabel();
        AUX = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        num1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        num3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        num2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        lblvotop.setBackground(new java.awt.Color(255, 255, 255));
        lblvotop.setText("SEU VOTO PARA ");

        jLabel1.setText("NÚMERO:");

        Partido.setText("PARTIDO");

        nomePartido.setText("NOME DO PARTIDO");

        jLabel6.setText("Senador");

        jLabel7.setText("Aperte a tecla:");

        jLabel8.setText("CONFIRMA para PROSSEGUIR");

        jLabel9.setText("CORRIGE para REINICIAR este voto ");

        Nome.setText("Nome");

        nomeCand.setText("Nome do Candidato");

        AUX.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        AUX.setText("AUX");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Partido, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomePartido, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addComponent(lblvotop, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(num1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(num2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(num3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomeCand, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(AUX, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblvotop, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nome)
                    .addComponent(nomeCand))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Partido)
                    .addComponent(nomePartido))
                .addGap(18, 18, 18)
                .addComponent(AUX, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(5, 5, 5)
                .addComponent(jLabel9)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(0, 0, 0));
        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(0, 0, 0));
        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("0");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(0, 0, 0));
        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(0, 0, 0));
        jButton10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("8");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton11.setText("BRANCO");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setBackground(new java.awt.Color(255, 130, 0));
        jButton12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton12.setText("CORRIGE");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setBackground(new java.awt.Color(0, 255, 0));
        jButton13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton13.setText("CONFIRMA");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(103, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(317, Short.MAX_VALUE)
                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(23, 23, 23)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(330, Short.MAX_VALUE)
                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(44, 44, 44)))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(aux==0){
            num1.setText("1");
            aux++;
        }else if(aux==1){
            num2.setText("1");
            aux++;
        }else if(aux==2){
            num3.setText("1");
            aux++;
        }
        
     
        
        if(!(num1.getText().equals(""))&&!(num2.getText().equals(""))&&partido==false){
            String b=num1.getText()+num2.getText();
           
            for(int i=0;i<5;i++){
                if(b.equals(String.valueOf(numpartido[i]))){
                    Partido.setText("Partido:");
                    nomePartido.setText(nomepartido[i]);
                    partido=true;
                }
            }
        }
        
        
        /*verifica se todos os campos estão preenchidos, se estiver, compara os números com os candidatos precadastrado
        e se o candidato estiver cadastrado, envia o nome do candidato para a tela principal */
       
        if(!(num1.getText().equals(""))&&!(num2.getText().equals(""))&&!(num3.getText().equals(""))){
            String a=num1.getText()+num2.getText()+num3.getText();
            boolean auxLocal=true;
            for(int i=0;i<5;i++){

                if(a.equals(String.valueOf(num[i]))){
                    
                    Nome.setText("Nome:");
                    nomeCand.setText(senador[i]);
                    auxLocal=false;
                }
                
            }
            //Para o caso de o voto ser nulo
                if(auxLocal==true){
                    nomeCand.setText("Número Errado");
                    Partido.setText("");
                    nomePartido.setText("");
                    AUX.setText("Voto Nulo");
                }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(aux==0){
            num1.setText("2");
            aux++;
        }else if(aux==1){
            num2.setText("2");
            aux++;
        }else if(aux==2){
            num3.setText("2");
            aux++;
        }
        
         if(!(num1.getText().equals(""))&&!(num2.getText().equals(""))&&partido==false){
            String b=num1.getText()+num2.getText();
           
            for(int i=0;i<5;i++){
                if(b.equals(String.valueOf(numpartido[i]))){
                    Partido.setText("Partido:");
                    nomePartido.setText(nomepartido[i]);
                    partido=true;
                }
            }
        }
        
        
        /*verifica se todos os campos estão preenchidos, se estiver, compara os números com os candidatos precadastrado
        e se o candidato estiver cadastrado, envia o nome do candidato para a tela principal */
       
        if(!(num1.getText().equals(""))&&!(num2.getText().equals(""))&&!(num3.getText().equals(""))){
            String a=num1.getText()+num2.getText()+num3.getText();
            boolean auxLocal=true;
            for(int i=0;i<5;i++){

                if(a.equals(String.valueOf(num[i]))){
                    
                    Nome.setText("Nome:");
                    nomeCand.setText(senador[i]);
                    auxLocal=false;
                }
                
            }
            //Para o caso de o voto ser nulo
                if(auxLocal==true){
                    nomeCand.setText("Número Errado");
                    Partido.setText("");
                    nomePartido.setText("");
                    AUX.setText("Voto Nulo");
                }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(aux==0){
            num1.setText("3");
            aux++;
        }else if(aux==1){
            num2.setText("3");
            aux++;
        }else if(aux==2){
            num3.setText("3");
            aux++;
        }
        
         /*verifica se todos os campos estão preenchidos, se estiver, compara os números com os candidatos precadastrado
        e se o candidato estiver cadastrado, envia o nome do candidato para a tela principal */
        
        if(!(num1.getText().equals(""))&&!(num2.getText().equals(""))&&partido==false){
            String b=num1.getText()+num2.getText();
           
            for(int i=0;i<5;i++){
                if(b.equals(String.valueOf(numpartido[i]))){
                    Partido.setText("Partido:");
                    nomePartido.setText(nomepartido[i]);
                    partido=true;
                }
            }
        }
        
        
        /*verifica se todos os campos estão preenchidos, se estiver, compara os números com os candidatos precadastrado
        e se o candidato estiver cadastrado, envia o nome do candidato para a tela principal */
       
        if(!(num1.getText().equals(""))&&!(num2.getText().equals(""))&&!(num3.getText().equals(""))){
            String a=num1.getText()+num2.getText()+num3.getText();
            boolean auxLocal=true;
            for(int i=0;i<5;i++){

                if(a.equals(String.valueOf(num[i]))){
                    
                    Nome.setText("Nome:");
                    nomeCand.setText(senador[i]);
                    auxLocal=false;
                }
                
            }
            //Para o caso de o voto ser nulo
                if(auxLocal==true){
                    nomeCand.setText("Número Errado");
                    Partido.setText("");
                    nomePartido.setText("");
                    AUX.setText("Voto Nulo");
                }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
       
        
        
        if(auxBranco==false){
            if(!(num1.getText().equals(""))&&!(num2.getText().equals(""))&&!(num3.getText().equals(""))){
                
                int a=Integer.valueOf(num1.getText()+num2.getText()+num3.getText());
                validacao(a);
                concluir=1;
                
                Senador.this.dispose();
                
            }
        
        }else{
           validaBranco(auxBranco);
           concluir=1;
         
           Senador.this.dispose();
         
        }
        
        
        
        
        
        
     
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        /*verifica se todos os campos estão preenchidos, se estiver, compara os números com os candidatos precadastrado
        e se o candidato estiver cadastrado, envia o nome do candidato para a tela principal */
         if(aux==0){
            num1.setText("4");
            aux++;
        }else if(aux==1){
            num2.setText("4");
            aux++;
        }else if(aux==2){
            num3.setText("4");
            aux++;
        }
        
         if(!(num1.getText().equals(""))&&!(num2.getText().equals(""))&&partido==false){
            String b=num1.getText()+num2.getText();
           
            for(int i=0;i<5;i++){
                if(b.equals(String.valueOf(numpartido[i]))){
                    Partido.setText("Partido:");
                    nomePartido.setText(nomepartido[i]);
                    partido=true;
                }
            }
        }
        
        
        /*verifica se todos os campos estão preenchidos, se estiver, compara os números com os candidatos precadastrado
        e se o candidato estiver cadastrado, envia o nome do candidato para a tela principal */
       
        if(!(num1.getText().equals(""))&&!(num2.getText().equals(""))&&!(num3.getText().equals(""))){
            String a=num1.getText()+num2.getText()+num3.getText();
            boolean auxLocal=true;
            for(int i=0;i<5;i++){

                if(a.equals(String.valueOf(num[i]))){
                    
                    Nome.setText("Nome:");
                    nomeCand.setText(senador[i]);
                    auxLocal=false;
                }
                
            }
            //Para o caso de o voto ser nulo
                if(auxLocal==true){
                    nomeCand.setText("Número Errado");
                    Partido.setText("");
                    nomePartido.setText("");
                    AUX.setText("Voto Nulo");
                }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        
       //Reseta todos as atribuições
        aux=0;
        numNulo=false;
        numBranco=false;
        partido=false;
        num1.setText("");
        num2.setText("");
        num3.setText("");
        Partido.setText("");
        nomePartido.setText("");
        Nome.setText("");
        nomeCand.setText("");
        AUX.setText("");
        
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if(aux==0){
            num1.setText("5");
            aux++;
        }else if(aux==1){
            num2.setText("5");
            aux++;
        }else if(aux==2){
            num3.setText("5");
            aux++;
        }
        
         if(!(num1.getText().equals(""))&&!(num2.getText().equals(""))&&partido==false){
            String b=num1.getText()+num2.getText();
           
            for(int i=0;i<5;i++){
                if(b.equals(String.valueOf(numpartido[i]))){
                    Partido.setText("Partido:");
                    nomePartido.setText(nomepartido[i]);
                    partido=true;
                }
            }
        }
        
        
        /*verifica se todos os campos estão preenchidos, se estiver, compara os números com os candidatos precadastrado
        e se o candidato estiver cadastrado, envia o nome do candidato para a tela principal */
       
        if(!(num1.getText().equals(""))&&!(num2.getText().equals(""))&&!(num3.getText().equals(""))){
            String a=num1.getText()+num2.getText()+num3.getText();
            boolean auxLocal=true;
            for(int i=0;i<5;i++){

                if(a.equals(String.valueOf(num[i]))){
                    
                    Nome.setText("Nome:");
                    nomeCand.setText(senador[i]);
                    auxLocal=false;
                }
                
            }
            //Para o caso de o voto ser nulo
                if(auxLocal==true){
                    nomeCand.setText("Número Errado");
                    Partido.setText("");
                    nomePartido.setText("");
                    AUX.setText("Voto Nulo");
                }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if(aux==0){
            num1.setText("6");
            aux++;
        }else if(aux==1){
            num2.setText("6");
            aux++;
        }else if(aux==2){
            num3.setText("6");
            aux++;
        }
        
if(!(num1.getText().equals(""))&&!(num2.getText().equals(""))&&partido==false){
            String b=num1.getText()+num2.getText();
           
            for(int i=0;i<5;i++){
                if(b.equals(String.valueOf(numpartido[i]))){
                    Partido.setText("Partido:");
                    nomePartido.setText(nomepartido[i]);
                    partido=true;
                }
            }
        }
        
        
        /*verifica se todos os campos estão preenchidos, se estiver, compara os números com os candidatos precadastrado
        e se o candidato estiver cadastrado, envia o nome do candidato para a tela principal */
       
        if(!(num1.getText().equals(""))&&!(num2.getText().equals(""))&&!(num3.getText().equals(""))){
            String a=num1.getText()+num2.getText()+num3.getText();
            boolean auxLocal=true;
            for(int i=0;i<5;i++){

                if(a.equals(String.valueOf(num[i]))){
                    
                    Nome.setText("Nome:");
                    nomeCand.setText(senador[i]);
                    auxLocal=false;
                }
                
            }
            //Para o caso de o voto ser nulo
                if(auxLocal==true){
                    nomeCand.setText("Número Errado");
                    Partido.setText("");
                    nomePartido.setText("");
                    AUX.setText("Voto Nulo");
                }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        if(aux==0){
            num1.setText("7");
            aux++;
        }else if(aux==1){
            num2.setText("7");
            aux++;
        }else if(aux==2){
            num3.setText("7");
            aux++;
        }
        
         if(!(num1.getText().equals(""))&&!(num2.getText().equals(""))&&partido==false){
            String b=num1.getText()+num2.getText();
           
            for(int i=0;i<5;i++){
                if(b.equals(String.valueOf(numpartido[i]))){
                    Partido.setText("Partido:");
                    nomePartido.setText(nomepartido[i]);
                    partido=true;
                }
            }
        }
        
        
        /*verifica se todos os campos estão preenchidos, se estiver, compara os números com os candidatos precadastrado
        e se o candidato estiver cadastrado, envia o nome do candidato para a tela principal */
       
        if(!(num1.getText().equals(""))&&!(num2.getText().equals(""))&&!(num3.getText().equals(""))){
            String a=num1.getText()+num2.getText()+num3.getText();
            boolean auxLocal=true;
            for(int i=0;i<5;i++){

                if(a.equals(String.valueOf(num[i]))){
                    
                    Nome.setText("Nome:");
                    nomeCand.setText(senador[i]);
                    auxLocal=false;
                }
                
            }
            //Para o caso de o voto ser nulo
                if(auxLocal==true){
                    nomeCand.setText("Número Errado");
                    Partido.setText("");
                    nomePartido.setText("");
                    AUX.setText("Voto Nulo");
                }
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        if(aux==0){
            num1.setText("8");
            aux++;
        }else if(aux==1){
            num2.setText("8");
            aux++;
        }else if(aux==2){
            num3.setText("8");
            aux++;
        }
        
         if(!(num1.getText().equals(""))&&!(num2.getText().equals(""))&&partido==false){
            String b=num1.getText()+num2.getText();
           
            for(int i=0;i<5;i++){
                if(b.equals(String.valueOf(numpartido[i]))){
                    Partido.setText("Partido:");
                    nomePartido.setText(nomepartido[i]);
                    partido=true;
                }
            }
        }
        
        
        /*verifica se todos os campos estão preenchidos, se estiver, compara os números com os candidatos precadastrado
        e se o candidato estiver cadastrado, envia o nome do candidato para a tela principal */
       
        if(!(num1.getText().equals(""))&&!(num2.getText().equals(""))&&!(num3.getText().equals(""))){
            String a=num1.getText()+num2.getText()+num3.getText();
            boolean auxLocal=true;
            for(int i=0;i<5;i++){

                if(a.equals(String.valueOf(num[i]))){
                    
                    Nome.setText("Nome:");
                    nomeCand.setText(senador[i]);
                    auxLocal=false;
                }
                
            }
            //Para o caso de o voto ser nulo
                if(auxLocal==true){
                    nomeCand.setText("Número Errado");
                    Partido.setText("");
                    nomePartido.setText("");
                    AUX.setText("Voto Nulo");
                }
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        if(aux==0){
            num1.setText("9");
            aux++;
        }else if(aux==1){
            num2.setText("9");
            aux++;
        }else if(aux==2){
            num3.setText("9");
            aux++;
        }
        
        if(!(num1.getText().equals(""))&&!(num2.getText().equals(""))&&partido==false){
            String b=num1.getText()+num2.getText();
           
            for(int i=0;i<5;i++){
                if(b.equals(String.valueOf(numpartido[i]))){
                    Partido.setText("Partido:");
                    nomePartido.setText(nomepartido[i]);
                    partido=true;
                }
            }
        }
        
        
        /*verifica se todos os campos estão preenchidos, se estiver, compara os números com os candidatos precadastrado
        e se o candidato estiver cadastrado, envia o nome do candidato para a tela principal */
       
        if(!(num1.getText().equals(""))&&!(num2.getText().equals(""))&&!(num3.getText().equals(""))){
            String a=num1.getText()+num2.getText()+num3.getText();
            boolean auxLocal=true;
            for(int i=0;i<5;i++){

                if(a.equals(String.valueOf(num[i]))){
                    
                    Nome.setText("Nome:");
                    nomeCand.setText(senador[i]);
                    auxLocal=false;
                }
                
            }
            //Para o caso de o voto ser nulo
                if(auxLocal==true){
                    nomeCand.setText("Número Errado");
                    Partido.setText("");
                    nomePartido.setText("");
                    AUX.setText("Voto Nulo");
                }
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        if(aux==0){
            num1.setText("0");
            aux++;
        }else if(aux==1){
            num2.setText("0");
            aux++;
        }else if(aux==2){
            num3.setText("0");
            aux++;
        }
        
         if(!(num1.getText().equals(""))&&!(num2.getText().equals(""))&&partido==false){
            String b=num1.getText()+num2.getText();
           
            for(int i=0;i<5;i++){
                if(b.equals(String.valueOf(numpartido[i]))){
                    Partido.setText("Partido:");
                    nomePartido.setText(nomepartido[i]);
                    partido=true;
                }
            }
        }
        
        
        /*verifica se todos os campos estão preenchidos, se estiver, compara os números com os candidatos precadastrado
        e se o candidato estiver cadastrado, envia o nome do candidato para a tela principal */
       
        if(!(num1.getText().equals(""))&&!(num2.getText().equals(""))&&!(num3.getText().equals(""))){
            String a=num1.getText()+num2.getText()+num3.getText();
            boolean auxLocal=true;
            for(int i=0;i<5;i++){

                if(a.equals(String.valueOf(num[i]))){
                    
                    Nome.setText("Nome:");
                    nomeCand.setText(senador[i]);
                    auxLocal=false;
                }
                
            }
            //Para o caso de o voto ser nulo
                if(auxLocal==true){
                    nomeCand.setText("Número Errado");
                    Partido.setText("");
                    nomePartido.setText("");
                    AUX.setText("Voto Nulo");
                }
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        auxBranco=true;
        AUX.setText("VOTO BRANCO");
    }//GEN-LAST:event_jButton11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Senador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Senador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Senador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Senador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Senador().setVisible(true);
              
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AUX;
    private javax.swing.JLabel Nome;
    private javax.swing.JLabel Partido;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblvotop;
    private javax.swing.JLabel nomeCand;
    private javax.swing.JLabel nomePartido;
    private javax.swing.JTextField num1;
    private javax.swing.JTextField num2;
    private javax.swing.JTextField num3;
    // End of variables declaration//GEN-END:variables
}
